# Generated by Django 3.2.5 on 2021-07-10 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phones', '0004_auto_20210710_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='صاحب دفترچه'),
        ),
    ]
