# Generated by Django 3.2.5 on 2021-07-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_entry_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'دفترچه تلفن', 'verbose_name_plural': 'دفترچه تلفن ها'},
        ),
    ]
